name: .NET Core

on:
  push:
    branches:       
      - main
  pull_request:
    branches: 
      - main
jobs:  
  build:
    env:
      TESTS_PROJECT: 'GrpahTests/GrpahTest.csproj.csproj' # path to test project or solution
      PUBLISH_NUGET: false # if true a nuget will be published on version change
      RUN_TESTS: true # if true tests are run and coverage data is published to coveralls and a coverage report is produced.
      MAIN_CSPROJ: 'Client/Client.csproj' # main project (for nuget packaging)
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Clean artifacts and nugets 
      run: dotnet clean  --configuration Release && dotnet nuget locals all --clear   
    - name: innfo
      run: dotnet --info                    
    - name: dotnet publish            
      run: dotnet -c Release -o release --nologo      
    - name: refresh coverage badge
      uses: fjogeleit/http-request-action@master
      with:
        url: https://camo.githubusercontent.com/12c4fcb3b21fbb2a725fc61449fb1b91e972c4c8a2baaf5904936d8e334bdbe8/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f62336230302f63736c792f62616467652e7376673f6272616e63683d64657626736572766963653d676974687562
        method: PURGE
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
